### ISSUE TITLE
Migrate under Template/Tag fails on PHP 7.1

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#490]
Migrate under Template/Tag fails on PHP 7.1

```Fatal error: Uncaught ArgumentCountError: Too few arguments to function extras(), 0 passed and exactly 1 expected in /www/htdocs/w00976cb/redaxscript-demo/includes/contents.php:271 Stack trace: #0 [internal function]: extras() #1 /www/htdocs/w00976cb/redaxscript-demo/includes/Template/Tag.php(372): call_user_func_array('extras', Array) #2 /www/htdocs/w00976cb/redaxscript-demo/includes/Template/Tag.php(280): Redaxscript\Template\Tag::_migrate('extras') #3 /www/htdocs/w00976cb/redaxscript-demo/templates/default/sidebar.phtml(7): Redaxscript\Template\Tag::extra() #4 /www/htdocs/w00976cb/redaxscript-demo/includes/Template/Tag.php(200): include('/www/htdocs/w00...') #5 /www/htdocs/w00976cb/redaxscript-demo/templates/default/main.phtml(33): Redaxscript\Template\Tag::partial(Array) #6 /www/htdocs/w00976cb/redaxscript-demo/includes/Template/Tag.php(200): include('/www/htdocs/w00...') #7 /www/htdocs/w00976cb/redaxscript-demo/templates/default/index.phtml(21): Redaxscript\Template\Tag::partial(Array) #8 /www/htdocs/w00976cb/redaxsc in /www/htdocs/w00976cb/redaxscript-demo/includes/contents.php on line 271```

**Comment by redaxmedia** [comment]
Done
